Clarify what autogenerate compares
sqlalchemy/alembic pull request #1570
Opened 2024-11-05 19:09 UTC by peterjc

### Description

I was struggling with empty upgrade/downgrade functions because both my database and my ORM were up to date. I wrongly assumed the comparison was against the previous database scheme as per the prior revision script(s).

### Checklist

This pull request is:

- [x] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

2024-11-05 19:14 UTC, peterjc commented
Cross reference https://github.com/sqlalchemy/alembic/discussions/1086

2024-11-05 19:23 UTC, zzzeek requested changes
I think the term "previous" and "latest" are confusing, since these terms are just being introduced here without much context

2024-11-05 19:23 UTC, zzzeek commented on docs/build/autogenerate.rst
> +your ``alemic.ini`` file using the *previous* schema) and compare against the
"current" schema

2024-11-05 19:23 UTC, zzzeek commented on docs/build/autogenerate.rst
> +table metadata in the application (your ORM which defines the *latest* schema),
"proposed" schema

2024-11-05 21:00 UTC, peterjc commented
Your suggested terminology is clear to me too; updated.

2024-11-06 17:06 UTC, zzzeek approved these changes

2024-11-07 14:51 UTC, sqla-tester reviewed
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision dec968b136a813d27e1d2bca04574a2399343a1a of this pull request into gerrit so we can run tests and reviews and stuff

2024-11-07 14:51 UTC, sqla-tester commented
New Gerrit review created for change dec968b136a813d27e1d2bca04574a2399343a1a: https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/5588

2024-11-07 19:16 UTC, sqla-tester commented
**Federico Caselli** (CaselIT) wrote:

not 100% correct, but I guess it's generally right

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/5588

2024-11-07 19:49 UTC, sqla-tester commented
**Michael Bayer** (zzzeek) wrote:

agree close enough thanks for the review

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/5588

2024-11-07 19:49 UTC, sqla-tester commented
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/5588 has been **merged**. Congratulations! :)

2024-11-07 19:49 UTC, closed without merging